name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
  blackducksca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          blackducksca_fixpr_enabled: true
          blackducksca_reports_sarif_create: true
          blackducksca_upload_sarif_report: true
          detect_args: '--detect.accuracy.required=NONE'
